export const packages = [
  {
    id: 1,
    name: "Bali Adventure: Island Hopping",
    image: "https://images.pexels.com/photos/3225531/pexels-photo-3225531.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    location: "Bali, Indonesia",
    duration: "7 Days",
    groupSize: "10 People",
    price: 1299,
    discount: 15,
    startDate: "2025-05-15",
    featured: true,
    description: "Experience the best of Bali with this 7-day island hopping adventure, including temples, beaches, and local culture.",
    activities: ["Beach", "Culture", "Adventure"],
    rating: 4.8,
    country: "Indonesia",
    highlights: [
      "Visit ancient temples",
      "Tea ceremony experience",
      "Geisha district tour",
      "Japanese cooking class",
    ],
    included: [
      "Traditional ryokan stay",
      "Daily breakfast",
      "JR Pass",
      "Guided cultural tours",
    ]
  },
  {
    id: 2,
    name: "Greek Islands Discovery",
    image: "https://images.pexels.com/photos/1430677/pexels-photo-1430677.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    location: "Santorini & Mykonos, Greece",
    duration: "10 Days",
    groupSize: "12 People",
    price: 2199,
    discount: 0,
    startDate: "2025-06-10",
    featured: true,
    description: "Explore the stunning Greek islands with this 10-day tour, including Santorini's sunset views and Mykonos' vibrant nightlife.",
    activities: ["Beach", "Culture", "Romantic"],
    rating: 4.9,
    country: "Indonesia",
    highlights: [
      "Visit ancient temples",
      "Tea ceremony experience",
      "Geisha district tour",
      "Japanese cooking class",
    ],
    included: [
      "Traditional ryokan stay",
      "Daily breakfast",
      "JR Pass",
      "Guided cultural tours",
    ]
  },
  {
    id: 3,
    name: "Japan Heritage Tour",
    image: "https://images.pexels.com/photos/5340085/pexels-photo-5340085.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    location: "Tokyo, Kyoto & Osaka, Japan",
    duration: "12 Days",
    groupSize: "14 People",
    price: 2799,
    discount: 10,
    startDate: "2025-04-01",
    featured: true,
    description: "Immerse yourself in Japanese culture with this 12-day tour, visiting ancient temples, modern cities, and serene gardens.",
    activities: ["Culture", "History", "Food"],
    rating: 4.7,
    country: "Indonesia",
    highlights: [
      "Visit ancient temples",
      "Tea ceremony experience",
      "Geisha district tour",
      "Japanese cooking class",
    ],
    included: [
      "Traditional ryokan stay",
      "Daily breakfast",
      "JR Pass",
      "Guided cultural tours",
    ]
  },
  {
    id: 4,
    name: "Machu Picchu & Sacred Valley",
    image: "https://images.pexels.com/photos/2356045/pexels-photo-2356045.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    location: "Cusco & Machu Picchu, Peru",
    duration: "8 Days",
    groupSize: "8 People",
    price: 1799,
    discount: 0,
    startDate: "2025-07-20",
    featured: false,
    description: "Hike the Inca Trail and discover the mysteries of Machu Picchu and the Sacred Valley on this 8-day adventure.",
    activities: ["Hiking", "History", "Adventure"],
    rating: 4.9,
    country: "Indonesia",
    highlights: [
      "Visit ancient temples",
      "Tea ceremony experience",
      "Geisha district tour",
      "Japanese cooking class",
    ],
    included: [
      "Traditional ryokan stay",
      "Daily breakfast",
      "JR Pass",
      "Guided cultural tours",
    ]
  },
  {
    id: 5,
    name: "African Safari: Wildlife Discovery",
    image: "https://images.pexels.com/photos/33045/lion-wild-africa-african.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    location: "Kenya & Tanzania",
    duration: "10 Days",
    groupSize: "6 People",
    price: 3299,
    discount: 5,
    startDate: "2025-09-05",
    featured: false,
    description: "Witness the Big Five and the Great Migration on this 10-day safari adventure through Kenya and Tanzania.",
    activities: ["Wildlife", "Nature", "Photography"],
    rating: 4.8,
    country: "Indonesia",
    highlights: [
      "Visit ancient temples",
      "Tea ceremony experience",
      "Geisha district tour",
      "Japanese cooking class",
    ],
    included: [
      "Traditional ryokan stay",
      "Daily breakfast",
      "JR Pass",
      "Guided cultural tours",
    ]
  },
  {
    id: 6,
    name: "Northern Lights Expedition",
    image: "https://images.pexels.com/photos/1693095/pexels-photo-1693095.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    location: "Iceland",
    duration: "6 Days",
    groupSize: "12 People",
    price: 2499,
    discount: 0,
    startDate: "2025-01-15",
    featured: false,
    description: "Chase the Northern Lights, explore ice caves, and relax in geothermal hot springs on this 6-day Icelandic adventure.",
    activities: ["Nature", "Photography", "Adventure"],
    rating: 4.7,
    country: "Indonesia",
    highlights: [
      "Visit ancient temples",
      "Tea ceremony experience",
      "Geisha district tour",
      "Japanese cooking class",
    ],
    included: [
      "Traditional ryokan stay",
      "Daily breakfast",
      "JR Pass",
      "Guided cultural tours",
    ]
  },
];